language: cpp
dist: bionic
compiler: gcc

# Boost
addons: 
  apt: 
    packages: 
      - libboost-all-dev
      - libboost-graph-dev

install: 
  - sudo apt install libboost-all-dev
  - sudo apt install libboost-graph-dev

script: 
  - qmake
  - make --silent
  - ./travis_qmake_gcc_cpp17_boost
