language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev

script: 
  - qmake
  - make --silent
  - ./travis_qmake_gcc_cpp17_boost
